# Configuring a single laptop (all devices local)

# Makefile interrogates the OS to find available devices. This is extended to network systems.

SYSTEM 1
  OS-GENERIC: Darwin
  WARNS: None
  ERRORS: None
  - DEVICE 1
    ARCH-GENERIC: arm64
    FRAMEWORKS: Accelerate
    INTRINSICS: NEON
