# WORKSPACE

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Protobuf
http_archive(
    name = "protobuf",
    sha256 = "c29d8b4b79389463c546f98b15aa4391d4ed7ec459340c47bffe15db63eb9126",
    strip_prefix = "protobuf-3.21.3",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.21.3.tar.gz"],
)

# gRPC
http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/b8a04acbbf18fd1c805e5d53d62ed9fa4721a4d1.tar.gz",
    ],
    strip_prefix = "grpc-b8a04acbbf18fd1c805e5d53d62ed9fa4721a4d1",
    integrity = "sha256-kawBH0HrDWR8cQTF7/ZmaLUUpnNbpETui8TinPXeMYk=",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()

# C++ Rules
http_archive(
    name = "rules_cc",
    urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.17/rules_cc-0.0.17.tar.gz"],
    sha256 = "4dccbfd22c0def164c8f47458bd50e0c7148f3d92002cdb459c2a96a68498241",
)

# LibTorch
http_archive(
    name = "libtorch",
    urls = ["https://download.pytorch.org/libtorch/cpu/libtorch-macos-arm64-2.4.0.zip"],
    strip_prefix = "libtorch",
    build_file_content = """
cc_library(
    name = "libtorch",
    srcs = glob([
        "lib/libc10.dylib",
        "lib/libfbjni.dylib",
        "lib/libomp.dylib",
        "lib/libpytorch_jni.dylib",
        "lib/libshm.dylib",
        "lib/libtorch.dylib",
        "lib/libtorch_cpu.dylib",
        "lib/libtorch_global_deps.dylib",
        "lib/*.so",
        "lib/*.dll",
        "lib/*.a",
    ]),
    hdrs = glob([
        "include/**/*.h",
        "include/**/*.hpp",
        "include/**/*.cuh",
    ]),
    includes = [
        "include",
        "include/torch/csrc/api/include",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    copts = [
        "-std=c++17",
    ],
)
""",
)

# FlatBuffers
http_archive(
    name = "flatbuffers",
    urls = ["https://github.com/google/flatbuffers/archive/refs/tags/v24.3.25.zip"],
    integrity="sha256-5wb162yo944je/P37M/6HF7JqW08HJOPCNwJqrGIRSg=",
    strip_prefix = "flatbuffers-24.3.25",
    build_file_content = """
cc_library(
    name = "flatbuffers_lib",
    hdrs = glob(["include/flatbuffers/**/*.h"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
)
""",
)

# Precompiled flatc binary
http_archive(
    name = "flatc_prebuilt",
    urls = ["https://github.com/google/flatbuffers/releases/download/v24.3.25/Mac.flatc.binary.zip"],
    strip_prefix = "",
    integrity = "sha256-J3J09OEDfbtXsblXGXIf49WMhpg9Y0EDKErYwdnPGd0=",
    build_file_content = """
exports_files(["flatc"])
""",
)
